import type { Metadata } from 'next'
import LayerTabs from '@/components/LayerTabs'

export const metadata: Metadata = { title: 'Four Graph Layers: Breeze.AI' }

export default function GraphLayers() {
  return (
    <section className="docs-section">
      <h1>Four Graph Layers</h1>
      <p>Every artifact in software delivery maps to one of four connected ontologies. The Functional layer is the anchor layer: every other layer is traversable from it.</p>
      <LayerTabs />

      <h2 id="layer-reference">Layer reference</h2>
      <div className="doc-table-wrap" style={{ marginTop: 16 }}>
        <table className="doc-table">
          <thead><tr><th>Layer</th><th>Hierarchy</th><th>What it captures</th></tr></thead>
          <tbody>
            <tr><td><code>Functional</code></td><td>Persona → Outcome → Scenario → Step → Action</td><td>Who uses the product, what they want to achieve, and the exact actions they take. Anchor layer.</td></tr>
            <tr><td><code>Architecture</code></td><td>User Experience · API Gateway · Services · Agents · Event Queue · Data Lake · Observability · Infrastructure</td><td>The 8-layer system blueprint. Services, components, integration contracts, deployment topology.</td></tr>
            <tr><td><code>Design</code></td><td>Atom → Molecule → Organism → Template → Page (+ UserJourney → Flow)</td><td>Atomic-design model of the UI. Links each component back to the user outcome that justifies it.</td></tr>
            <tr><td><code>Code</code></td><td>File → Class → Function → Statement → Api</td><td>Auto-generated by the Code Ontology Generator from real source. Bridges architecture to implementation.</td></tr>
          </tbody>
        </table>
      </div>
    </section>
  )
}
